
 create table WX_VOTE_RESULT ( 
    ID_ NUMBER(19,0)  not null ,
    ACTORID_ NVARCHAR2  (50) ,
    IP_ NVARCHAR2  (200) ,
    RESULT_ NVARCHAR2  (500) ,
    VOTEDATE_ TIMESTAMP(6) ,
    VOTEID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_VOTE_ITEM ( 
    ID_ NUMBER(19,0)  not null ,
    NAME_ NVARCHAR2  (200) ,
    VALUE_ NVARCHAR2  (20) ,
    VOTEID_ NUMBER(19,0) ,
    ICON_ NVARCHAR2  (150) ,
    SORT_ INTEGER ,
    URL_ NVARCHAR2  (500) ,
    primary key (ID_) 
);


 create table WX_VOTE ( 
    ID_ NUMBER(19,0)  not null ,
    CONTENT_ NVARCHAR2  (2048) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    DESC_ NVARCHAR2  (500) ,
    ENDDATE_ TIMESTAMP(6) ,
    ICON_ NVARCHAR2  (250) ,
    LIMITFLAG_ INTEGER ,
    LIMITTIMEINTERVAL_ INTEGER ,
    MULTIFLAG_ INTEGER ,
    SIGNFLAG_ INTEGER ,
    STARTDATE_ TIMESTAMP(6) ,
    STATUS_ INTEGER ,
    TITLE_ NVARCHAR2  (200) ,
    KEYWORDS_ NVARCHAR2  (100) ,
    RESULTFLAG_ INTEGER ,
    SHOWICONFLAG_ INTEGER ,
    ACCOUNTID_ NUMBER(19,0) ,
    RELATIONIDS_ NVARCHAR2  (100) ,
    SORT_ INTEGER ,
    primary key (ID_) 
);


 create table WX_USER_TEMPLATE ( 
    ID_ NUMBER(19,0)  not null ,
    CATEGORYID_ NUMBER(19,0) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    TEMPLATEID_ NUMBER(19,0) ,
    TYPE_ NVARCHAR2  (50) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_USER ( 
    ID NUMBER(19,0)  not null ,
    ACCOUNTTYPE INTEGER ,
    ACTORID NVARCHAR2  (50) ,
    APPID NUMBER(19,0) ,
    AREA NVARCHAR2  (200) ,
    CITY NVARCHAR2  (200) ,
    CREATEDATE TIMESTAMP(6) ,
    DEPTID NUMBER(19,0) ,
    ENDDATE TIMESTAMP(6) ,
    LOCKED INTEGER ,
    MAIL NVARCHAR2  (100) ,
    MOBILE NVARCHAR2  (20) ,
    NAME NVARCHAR2  (50) ,
    PROVINCE NVARCHAR2  (50) ,
    REMARK NVARCHAR2  (250) ,
    TELEPHONE NVARCHAR2  (50) ,
    TOKEN NVARCHAR2  (100) ,
    TYPE NVARCHAR2  (20) ,
    USERTYPE INTEGER ,
    WXHEADIMAGE NVARCHAR2  (250) ,
    WXSOURCEID NVARCHAR2  (50) ,
    WXID NVARCHAR2  (50) ,
    WXNAME NVARCHAR2  (50) ,
    YXHEADIMAGE NVARCHAR2  (250) ,
    YXSOURCEID NVARCHAR2  (50) ,
    YXID NVARCHAR2  (50) ,
    YXNAME NVARCHAR2  (50) ,
    LBSPOSITION INTEGER ,
    WXAPPID NVARCHAR2  (100) ,
    WXAPPSECRET NVARCHAR2  (100) ,
    YXAPPID NVARCHAR2  (100) ,
    YXAPPSECRET NVARCHAR2  (100) ,
    primary key (ID) 
);


 create table WX_TEMPLATE ( 
    ID_ NUMBER(19,0)  not null ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    DEFAULTFLAG_ INTEGER ,
    SKINID_ NVARCHAR2  (50) ,
    SKINIMAGE_ NVARCHAR2  (500) ,
    TYPE_ NVARCHAR2  (50) ,
    PATH_ NVARCHAR2  (500) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    LOCKED_ INTEGER ,
    CATEGORYID_ NUMBER(19,0) ,
    CONTENT_ CLOB   ,
    NAME_ NVARCHAR2  (100) ,
    DESC_ NVARCHAR2  (500) ,
    TEMPLATETYPE_ NVARCHAR2  (50) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_MODULE ( 
    ID_ NUMBER(19,0)  not null ,
    CODE_ NVARCHAR2  (50) ,
    CONTENT_ NVARCHAR2  (255) ,
    IDFIELD_ NVARCHAR2  (50) ,
    JSON_ NVARCHAR2  (500) ,
    LINK_ NVARCHAR2  (250) ,
    LINKTYPE_ NVARCHAR2  (50) ,
    LISTLINK_ NVARCHAR2  (250) ,
    LOCKED_ INTEGER ,
    MODULEID_ NVARCHAR2  (50) ,
    MODULENAME_ NVARCHAR2  (200) ,
    SQL_ NVARCHAR2  (2000) ,
    SUBJECTFIELD_ NVARCHAR2  (50) ,
    TITLE_ NVARCHAR2  (200) ,
    SORT_ INTEGER ,
    primary key (ID_) 
);


 create table WX_MESSAGE ( 
    ID_ NUMBER(19,0)  not null ,
    CONTENT_ NVARCHAR2  (2048) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    MOBILE_ NVARCHAR2  (50) ,
    NAME_ NVARCHAR2  (50) ,
    TITLE_ NVARCHAR2  (200) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_MENU ( 
    ID_ NUMBER(19,0)  not null ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    KEY_ NVARCHAR2  (200) ,
    NAME_ NVARCHAR2  (200) ,
    PARENT_ NUMBER(19,0) ,
    SORT_ INTEGER ,
    TYPE_ NVARCHAR2  (50) ,
    URL_ NVARCHAR2  (500) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    LOCKED_ INTEGER ,
    DESC_ NVARCHAR2  (500) ,
    GROUP_ NVARCHAR2  (50) ,
    ICON_ NVARCHAR2  (150) ,
    ICONCLS_ NVARCHAR2  (50) ,
    TREEID_ NVARCHAR2  (500) ,
    PICURL_ NVARCHAR2  (500) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_LOG ( 
    ID_ NUMBER(19,0)  not null ,
    ACCOUNTID_ NUMBER(19,0) ,
    ACTORID_ NVARCHAR2  (50) ,
    CONTENT_ NVARCHAR2  (500) ,
    CREATETIME_ TIMESTAMP(6) ,
    FLAG_ INTEGER ,
    IP_ NVARCHAR2  (100) ,
    OPENID_ NVARCHAR2  (200) ,
    OPERATE_ NVARCHAR2  (50) ,
    primary key (ID_) 
);


 create table WX_KEYWORDS ( 
    ID_ NUMBER(19,0)  not null ,
    CATEGORYID_ NUMBER(19,0) ,
    CONTENTID_ NUMBER(19,0) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    KEYWORDS_ NVARCHAR2  (250) ,
    KEYWORDSMATCHTYPE_ NVARCHAR2  (250) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_FOLLOWER ( 
    ID_ NUMBER(19,0)  not null ,
    ACCOUNTID_ NUMBER(19,0) ,
    ACTORID_ NVARCHAR2  (50) ,
    CITY_ NVARCHAR2  (100) ,
    COUNTRY_ NVARCHAR2  (100) ,
    CREATEDATE_ TIMESTAMP(6) ,
    HEADIMGURL_ NVARCHAR2  (500) ,
    LANGUAGE_ NVARCHAR2  (50) ,
    LOCKED_ INTEGER ,
    MAIL_ NVARCHAR2  (100) ,
    MOBILE_ NVARCHAR2  (20) ,
    NICKNAME_ NVARCHAR2  (200) ,
    OPENID_ NVARCHAR2  (200) ,
    PROVINCE_ NVARCHAR2  (100) ,
    REMARK NVARCHAR2  (250) ,
    SEX_ NVARCHAR2  (1) ,
    SUBSCRIBETIME_ NUMBER(19,0) ,
    TELEPHONE_ NVARCHAR2  (50) ,
    SOURCEID_ NVARCHAR2  (200) ,
    UNSUBSCRIBETIME_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_FILE ( 
    ID_ NUMBER(19,0)  not null ,
    CATEGORYID_ NUMBER(19,0) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    FILENAME_ NVARCHAR2  (200) ,
    PATH_ NVARCHAR2  (500) ,
    TITLE_ NVARCHAR2  (200) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    DESC_ NVARCHAR2  (500) ,
    LOCKED_ INTEGER ,
    ORIGINALFILENAME_ NVARCHAR2  (200) ,
    SIZE_ NUMBER(19,0) ,
    TYPE_ NVARCHAR2  (50) ,
    CONTENT_ CLOB   ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_CONTENT ( 
    ID_ NUMBER(19,0)  not null ,
    BIGICON_ NVARCHAR2  (150) ,
    CATEGORYID_ NUMBER(19,0) ,
    CONTENT_ CLOB   ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    ICON_ NVARCHAR2  (150) ,
    KEYWORDS_ NVARCHAR2  (250) ,
    KEYWORDSCOUNT_ INTEGER ,
    PRIORTY_ INTEGER ,
    SMALLICON_ NVARCHAR2  (150) ,
    STATUS_ INTEGER ,
    SUMMARY_ NVARCHAR2  (250) ,
    TITLE_ NVARCHAR2  (200) ,
    TYPE_ NVARCHAR2  (20) ,
    URL_ NVARCHAR2  (500) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    SORT_ INTEGER ,
    AUTHOR_ NVARCHAR2  (20) ,
    KEYWORDSMATCHTYPE_ NVARCHAR2  (255) ,
    RELATIONIDS_ NVARCHAR2  (100) ,
    RECOMMENDATIONIDS_ NVARCHAR2  (100) ,
    DETAILSHOWCOVER_ NVARCHAR2  (10) ,
    PICURL_ NVARCHAR2  (500) ,
    LABEL_ NVARCHAR2  (200) ,
    LOCATIONX_ NUMBER(*,10) ,
    LOCATIONY_ NUMBER(*,10) ,
    SCALE_ NVARCHAR2  (50) ,
    LATITUDE_ NUMBER(*,10) ,
    LONGITUDE_ NUMBER(*,10) ,
    MSGTYPE_ NVARCHAR2  (20) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table WX_CATEGORY ( 
    ID_ NUMBER(19,0)  not null ,
    CODE_ NVARCHAR2  (50) ,
    CREATEBY_ NVARCHAR2  (50) ,
    CREATEDATE_ TIMESTAMP(6) ,
    DESC_ NVARCHAR2  (500) ,
    EVENTTYPE_ NVARCHAR2  (50) ,
    ICON_ NVARCHAR2  (150) ,
    ICONCLS_ NVARCHAR2  (50) ,
    INDEXICON_ NVARCHAR2  (150) ,
    INDEXSHOW_ INTEGER ,
    LOCKED_ INTEGER ,
    NAME_ NVARCHAR2  (100) ,
    PARENT_ NUMBER(19,0) ,
    SORT_ INTEGER ,
    TREEID_ NVARCHAR2  (500) ,
    URL_ NVARCHAR2  (500) ,
    UUID_ NVARCHAR2  (50) ,
    LASTUPDATEBY_ NVARCHAR2  (50) ,
    LASTUPDATEDATE_ TIMESTAMP(6) ,
    TYPE_ NVARCHAR2  (50) ,
    COVERICON_ NVARCHAR2  (150) ,
    APPID_ NUMBER(19,0) ,
    ACCOUNTID_ NUMBER(19,0) ,
    primary key (ID_) 
);

